### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by define999** [spider863644/NS-LOOKUP#1]
Traceback (most recent call last):
  File "/home/thinhnlfx18071/NS-LOOKUP/nslookup.py", line 75, in <module>
    loop()
  File "/home/thinhnlfx18071/NS-LOOKUP/nslookup.py", line 18, in loop
    head = pyfiglet.figlet_format("NS-Lookup")
NameError: name 'pyfiglet' is not defined

**Comment by spider863644** [comment]
This means you just installed terms

I'll fix this soon and I'll get back to you

Thanks for the feedback

**Comment by define999** [comment]
im using termux btw

**Comment by spider863644** [comment]
I've fixed it

Now open termux and type the following command

rm -r -f NS-LOOKUP

This will delete the current repository, then install it again

**Comment by define999** [comment]
thanks dude works now!

**Comment by spider863644** [comment]
You are welcome

Kindly leave a follow and share

Stay tuned for more tools
